### PR TITLE
think.py

### PR DESCRIPTION
**Pull request by parth0207**
Oof

### CODE REVIEW

**Comment by New-dev0** [comment]
🤔

**Comment by New-dev0** [comment]
🤔

**Comment by sppidy** [comment]
I think I may close this pull request

**Comment by parth0207** [comment]
> I think I may close this pull request

No Animations?

**Comment by parth0207** [comment]
> I think I may close this pull request

No Animations?

**Comment by ArnabXD** [comment]
nope , no more animations in official addons

**Pull request closed without merging**
