### PR TITLE
Important features and 1 plugin

### PR DESCRIPTION
**Pull request by BLUE-DEVIL1134**
# Credits [@AKASH_AM1](https://t.me/AKASH_AM1)
# Created for Ultroid < https://github.com/TeamUltroid/Ultroid >

### CODE REVIEW

**Comment by ProgrammingError** [comment]
https://t.me/c/1237141420/247174

**Comment by BLUE-DEVIL1134** [comment]
> https://t.me/c/1237141420/247174

that seriously ment wait

**Comment by ProgrammingError** [comment]
> > https://t.me/c/1237141420/247174
> 
> that seriously ment wait

No One cares

**Comment by BLUE-DEVIL1134** [comment]
> > > https://t.me/c/1237141420/247174
> > 
> > 
> > that seriously ment wait
> 
> No One cares

:sed:

**Comment by BLUE-DEVIL1134** [comment]
If i see its closed without being merged, will reopen and merge moi self...

**Comment by BLUE-DEVIL1134** [comment]
fucking devs are not mentioning where to add prs and bmlaming users...

**Pull request closed without merging**
