### PR TITLE
Very useful

### PR DESCRIPTION
**Pull request by maxxy231**
This was the reason that i deployed hellbot. Now because of heroku i cant use that. So please add it in ultroid

### CODE REVIEW

**Comment by xditya** [comment]
There is already the same thing, it's command is .qbot.

**Comment by maxxy231** [comment]
> There is already the same thing, it's command is .qbot.

This one is different. We can choose colour of sticker. By 
.cqbot red <reply to text msg>

**Comment by New-dev0** [comment]
> > There is already the same thing, it's command is .qbot.
> 
> This one is different. We can choose colour of sticker. By
> .cqbot red

Ok , will add that , but in some command

**Comment by maxxy231** [comment]
> > > There is already the same thing, it's command is .qbot.
> > 
> > 
> > This one is different. We can choose colour of sticker. By
> > .cqbot red
> 
> Ok , will add that , but in some command

Thanks 😉

**Pull request closed without merging**
