### PR TITLE
Code renew 😂😂

### PR DESCRIPTION
**Pull request by errorshivansh**
@1Danish-00 @buddhhu @New-dev0

### CODE REVIEW

**Comment by buddhhu** [comment]
@errorshivansh It would have been nice if it was worthy

**Comment by New-dev0** [comment]
> @errorshivansh It would have been nice if it was worthy

+

**Comment by xditya** [comment]
🤔 no new plugins. Please stop trying to improve code quality. That is not what is needed here, rn.

**Comment by New-dev0** [comment]
Nvm, but dev branch is completely reformated and  changes done here are already there.

**Pull request closed without merging**
