### PR TITLE
successfully tested quotly

### PR DESCRIPTION
**Pull request by maxprogrammer007**
successfully tested quotly

### CODE REVIEW

**Review by ArnabXD — COMMENTED** [review]
seriously 😆 ? It already works fine

**Comment by maxprogrammer007** [comment]
ni pehle kaam ni krta tha shyd maine he commit kiya tha  me iz pro noob

**Comment by New-dev0** [comment]
Check commit history of that file in your repo

**Comment by maxprogrammer007** [comment]
bhaiya maine abhi 3 pr kiye hai woh tested hai unko merge krdo na

**Pull request closed without merging**
